# Site settings
title: Seho Kim blog
description: Deep Learning, Reinforcement Learning, Recommendation Systems, NLP, and etc.
email: prosh828@gmail.com
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

url: https://prosh828.github.io/
baseurl: ""
permalink: blog/:title/

markdown: kramdown

navigation:
 - title: Home
   url: /index
 - title: About
   url: /about
